Refactoring mia's
vliz-be-opsci/MIA pull request #1
Opened 2023-11-29 09:47 UTC by cedricdcc

Redone the Core approach on how the widget is constructed.

2023-12-04 10:48 UTC, marc-portier requested changes
sorry, limited time, so only ran over it quickly / diagonally
already some stuff to consider though

+ recommend finding an extra buddy in our team for this

2023-12-04 10:48 UTC, marc-portier commented on src/affordance_entity.js
> +        this.store = createEmptyStore();
what is this store about? every variable is there to 'store' something -- better to consider a name that hints at what it is about.

2023-12-04 10:48 UTC, marc-portier commented on src/affordance_entity.js
> +        this.NodeManipulations();
odd uppercase method name `NodeManipulations` -- suggests static which would be awkward

also `manipulations` is generic `doing` `function` `process` `method` all are not adding clear semantics about the actual purpose of this method -- so unhelpfully abstract

2023-12-04 10:48 UTC, marc-portier commented on src/affordance_entity.js
> +            if (storeSize(this.store) === 0 && !this.checked) {
odd external method? OO would suggest `this.store.size()` ??

2024-06-26 07:16 UTC, marc-portier approved these changes
out of interest -- do we have some automated tests for this module - if not now, somewhere in the planning?

2024-06-26 07:41 UTC, cedricdcc commented
> out of interest -- do we have some automated tests for this module - if not now, somewhere in the planning?

These will be added in the future

2024-06-28 11:44 UTC, merged